on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          # pip install mkdocs==1.6.0
          pip install mkdocs-material

      - run: |
          mkdocs build

      - run: |
          mkdir -p site/api/

      - uses: asyncapi/github-action-for-cli@v3.1.1
        with:
          command: generate
          filepath: api/asyncapi.yaml
          template: '@asyncapi/html-template@2.1.7'
          output: site/api/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-documents-${{ github.sha }}
          path: site/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 


      - run: mkdocs gh-deploy --force
