on:
  release:
    types:
      - published

jobs:
  build-client:
    needs: create-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneOSX
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: client
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2022.3.9f1

      - run: |
          mkdir -p release
          cp CHANGELOG.md COPYING README.md release/
          cp -r build/* release/

      - run: |
          zip -r ${{ github.event.repository.name }}-client-${{ matrix.targetPlatform }}.zip release/*

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-client-${{ matrix.targetPlatform }}.zip

  build-server:
    needs: create-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - win-arm64
          - win-x64
          - win-x86
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet publish src/GameServer -c Release -o bin \
          --sc false -r ${{ matrix.runtime }} -p:DebugType=none \
          -p:PublishSingleFile=true
        working-directory: server

      - run: |
          mkdir -p release
          cp CHANGELOG.md COPYING README.md release/
          cp -r server/bin/* release/

      - run: |
          zip -r ${{ github.event.repository.name }}-server-${{ matrix.runtime }}.zip release/*

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-server-${{ matrix.runtime }}.zip

  create-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}
